### ISSUE TITLE
Support for anonymous (unauthorised) comments

### ISSUE THREAD

**Issue by Dhravya** [giscus/giscus#406] opened 2022-02-17 14:05 UTC
I have giscus installed on my [blog](https://blog.dhravya.me), and some users suggested me to also enable anonymous comments.
Is it possible to add support for anonymous comments? Whenever someone sends the comment anonymously, giscus can do some basic moderation and the giscus github bot can send comments on behalf of the user. 
This will also need a way to delete comments, which can probably be done simply by deleting the discussion comment

Adding this feature will enable giscus to not be confined to a particular audience, and be an overall comment widget (which could be huge)
This may require some extra stuff though (like adding moderators, etc). I suggest, instead of adding those features make this an optional parameter disabled by default, so only small websites / blogs use this.

**Comment by nschonni** [comment] 2022-02-17 14:19
Duplicate of https://github.com/giscus/giscus/issues/65

**Closed** 2022-02-17 14:27 UTC
