### ISSUE TITLE
Fetch Failed

### ISSUE THREAD

**Issue by CheeseB** [giscus/giscus#1269] opened 2023-12-29 13:25 UTC
Hi,
#1250 this issue happened again 🥲 

![image](https://github.com/giscus/giscus/assets/43297823/24dcbd97-12c4-4b08-bf0e-1c42671cf241)

**Comment by mobeicanyue** [comment] 2023-12-29 13:39
same question

**Comment by Mikescops** [comment] 2023-12-29 14:24
Same here ☝️

**Comment by laymonage** [comment] 2023-12-29 14:32
I’m aware of the issue, but I’m on holidays I don’t have my laptop with me, so this probably won’t be fixed until the 2nd of January.

**Comment by CheeseB** [comment] 2023-12-29 14:37
Okay. thanks for the quick response :)

**Comment by mobeicanyue** [comment] 2023-12-29 14:40
How offen does this question happend? Is it normal, I used it for the first time today

**Comment by CheeseB** [comment] 2023-12-29 14:45
I've been using this for 9 months, but this is the first time I've had an issue like this.

**Comment by mobeicanyue** [comment] 2023-12-29 14:54
> I've been using this for 9 months, but this is the first time I've had an issue like this.

Ok I got it

**Comment by DSYZayn** [comment] 2023-12-29 15:14
same issue.My github page can fetch success but failed at `localhost development environment`.

**Comment by Mikescops** [comment] 2023-12-29 16:10
> I’m aware of the issue, but I’m on holidays and I don’t have my laptop with me, so this probably won’t be fixed until the 2nd of January.

Thanks for the answer!

Anything we can help you with to prevent this to happen in the future?

**Comment by mobeicanyue** [comment] 2023-12-29 16:51
> Thanks for the answer!
> 
> Anything we can help you with to prevent this to happen in the future?

We can only hope that the author's server runs smoothly. 😄 In my opinion, this project is open source, but it needs a server to run code that fetch GitHub discussions for us.

**Comment by hyoribogo** [comment] 2023-12-29 19:10
The same issue seems to be occurring on all websites. 😢

**Comment by yangdanny97** [comment] 2023-12-29 19:45
> I’m aware of the issue, but I’m on holidays and I don’t have my laptop with me, so this probably won’t be fixed until the 2nd of January.

Thanks for responding, and no rush, please enjoy the holidays!

This project has been a great addition to my site, so I dropped a small donation in the sponsor page - anyone else reading this who finds giscus useful and has some change to spare, I encourage you to do the same :)

**Comment by kangimc** [comment] 2023-12-29 22:59
I encountered the clock problem for the first time. How can I solve it?
Oh, my God, I just started using it for one day.

**Comment by mobeicanyue** [comment] 2023-12-30 02:27
I seems work now?
![image](https://github.com/giscus/giscus/assets/81098819/5aaa283c-1023-4c38-845c-e2cb4b705584)

**Comment by pourmand1376** [comment] 2023-12-30 08:20
I think there should be a way to fix this problem completely, not just fixing it ad-hoc (as this may also happen in the future).

**Comment by cha2hyun** [comment] 2023-12-30 12:52
same here 🥹

**Comment by yuanj82** [comment] 2023-12-30 14:04
Same here

**Comment by yuanj82** [comment] 2023-12-30 14:04
Same here

**Comment by omins** [comment] 2023-12-30 14:37
Same here 🥲

**Comment by Th1nhNg0** [comment] 2023-12-30 15:09
same here

**Comment by Ryrden** [comment] 2023-12-30 18:14
Same here

**Comment by EllaKaye** [comment] 2023-12-31 06:43
Commenting to follow. Enjoy your holiday @laymonage.

**Comment by Carrena-JW** [comment] 2023-12-31 07:22
Same here

**Comment by Matheart** [comment] 2023-12-31 10:38
Same here

**Comment by heli-os** [comment] 2023-12-31 10:48
Seems to be working fine now. is anyone else getting it to work?

ref: https://dataportal.kr/%EB%B8%94%EB%A1%9C%EA%B7%B8-%EC%9D%B4%EA%B4%80-%EB%B0%8F-%EC%95%9E%EC%9C%BC%EB%A1%9C%EC%9D%98-%EA%B3%84%ED%9A%8D/

![Screenshot 2023-12-31 at 7 48 10 PM](https://github.com/giscus/giscus/assets/44586666/6f7672a1-e9f2-478d-8727-d3eaf7727042)

cc. @laymonage

**Comment by ShwStone** [comment] 2023-12-31 11:16
The problem wasn't solved yet for me

**Comment by StefanKoell** [comment] 2023-12-31 11:23
doesn't work for me either. during troubleshooting (before I found this post) I even uninstalled giscus and started over. I'm not able to set it up again.

**Comment by maodaisuki** [comment] 2023-12-31 17:04
Same here🤯 and it's perfect in firefox but same error occurred in edge.

**Comment by Vanadiry** [comment] 2023-12-31 17:31
Same here

**Comment by alifeee** [comment] 2023-12-31 18:32
On one of my sites (<https://weeknotes.alifeee.co.uk/2023-52/>) giscus fails with a HTTP 403 error

![image](https://github.com/giscus/giscus/assets/13833017/b46d0ee4-3b89-47f3-8459-a72af0070504)

However, on another site (<https://blog.alifeee.co.uk/making-bogface/>), giscus works and the HTTP status code is 404

![image](https://github.com/giscus/giscus/assets/13833017/b60d7af5-9bab-4431-9d4d-fc8486ffb0a0)

The sites use very similar scripts, they are:

```diff
<script
  src="https://giscus.app/client.js"
- data-repo="alifeee/weeknotes"
+ data-repo="alifeee/blog"
- data-repo-id="R_kgDOK7knTw"
+ data-repo-id="R_kgDOJaqeLQ"
  data-category="comments"
- data-category-id="DIC_kwDOK7knT84Cb5SL"
+ data-category-id="DIC_kwDOJaqeLc4CZQST"
- data-mapping="pathname"
+ data-mapping="og:title"
  data-strict="1"
  data-reactions-enabled="1"
  data-emit-metadata="0"
- data-input-position="bottom"
+ data-input-position="top"
  data-theme="light"
  data-lang="en"
  crossorigin="anonymous"
  async=""
></script>
```

Perhaps the reason one works and the other does not is to do with this bit?

```diff
- data-mapping="pathname"
+ data-mapping="og:title"
```

(the `og:title` mapping site works, and the `pathname` mapping site does not work)

I do not know. Anyway, thank you for your work on this tool. It is very nice. Good day.

**Comment by heli-os** [comment] 2023-12-31 18:34
> I’m aware of the issue, but I’m on holidays and I don’t have my laptop with me, so this probably won’t be fixed until the 2nd of January.

to. @alifeee

**Comment by alifeee** [comment] 2023-12-31 18:40
> > I’m aware of the issue, but I’m on holidays and I don’t have my laptop with me, so this probably won’t be fixed until the 2nd of January.
> 
> to. @alifeee

Hi. What do you mean by this? I read that comment. But thanks for pointing it out to me.

**Comment by alifeee** [comment] 2023-12-31 18:46
to add to my above comment, giscus works on <https://weeknotes.alifeee.co.uk> when running on `localhost`, but not when running live on the server.

**Comment by wayneyaoo** [comment] 2023-12-31 19:05
> > > I’m aware of the issue, but I’m on holidays and I don’t have my laptop with me, so this probably won’t be fixed until the 2nd of January.
> > 
> > 
> > to. @alifeee
> 
> Hi. What do you mean by this? I read that comment. But thanks for pointing it out to me.

What he means is that you should stop posting "same here" reply and wait for the resolution because there're already enough "same here".

And please, for those "having the same issue" people, others might probably subscribe to this issue for fix notification. Such replies don't provide values but on the contrary could bury author's message. I thank you very much for being quiet and not spamming people's email. Happy new year.

**Comment by alifeee** [comment] 2023-12-31 19:08
> What he means is that you should stop posting "same here" reply and wait for the resolution because there're already enough "same here".

Hi, thanks for the concern. I agree. However, I looked into it a little and I considered that my input might be valuable, since I provided a reproducible difference case where it works/doesn't work.

I understand if you believe my comment to be a lengthy way of saying "same here", but I did not consider it as such, which is why I posted it. Thank you. Happy new year.

**Comment by kangimc** [comment] 2024-01-01 04:05
He seems to be working normally.

![Screenshot_2024-01-01-12-03-47-945_com microsoft emmx](https://github.com/giscus/giscus/assets/141106482/f7ef43c2-c072-44bb-a7f7-9e0fcaa6f142)

**Comment by kangimc** [comment] 2024-01-01 04:07
哦，他又不工作了
Oh, he doesn't work again.

**Comment by kangimc** [comment] 2024-01-01 04:12
### 为什么在部署在netlify可以正常工作
### Why can it work properly when deployed in netlify?
demonstrate
[https://imkang.netlify.app/2023/12/28/hexo/](https://imkang.netlify.app/2023/12/28/hexo/)

**Comment by Proskynete** [comment] 2024-01-01 05:38
Same error!
In local it's working, but not in production.
I have deploy my Astro project in vercel... 🥲

**Comment by kangimc** [comment] 2024-01-01 09:57
> 同样的错误！在本地，它正在工作，但在生产中却没有。我已经在 vercel 中部署了我的 Astro 项目......🥲

Yes

**Comment by kangimc** [comment] 2024-01-01 11:28
这是F12的调试结果
This is the debugging result of F12
<img width="314" alt="Snipaste_2024-01-01_19-24-56" src="https://github.com/giscus/giscus/assets/141106482/9e026014-efb0-43c6-afd4-b1938b494a52">

**Comment by shinyzhu** [comment] 2024-01-01 14:53
Same problem here.
Got 403 error of the giscus.app URL: https://giscus.app/api/discussions (with correctly configured params worked before.)

It might be error between the giscus app and GitHub.
Hope to recover soon.

**Comment by wey-gu** [comment] 2024-01-01 14:55
> I’m aware of the issue, but I’m on holidays and I don’t have my laptop with me, so this probably won’t be fixed until the 2nd of January.

Thank your time, please, it can wait for sure

**Comment by Xiang511** [comment] 2024-01-01 17:23
Same error
![image](https://github.com/giscus/giscus/assets/120042360/0784de09-3bcd-4d8c-9c28-956e7961e729)

**Comment by kangimc** [comment] 2024-01-01 18:01
> > 我知道这个问题，但我正在度假，我没有随身携带笔记本电脑，所以这可能要到 2 月 <> 日才能解决。
> 
> 谢谢你的时间，拜托，它肯定可以等待

I see.thanks

**Comment by laymonage** [comment] 2024-01-01 21:05
Should be fixed now. I forgot to check that the HTTPS certificate renewal works correctly after fixing #1271, hopefully this will never happen again. That said, if you heavily use the app, I'd really suggest self-hosting and not relying on the free service :)

**Closed by laymonage** 2024-01-01 21:05 UTC

**Comment by kangimc** [comment] 2024-01-02 01:02
> Should be fixed now. I forgot to check that the HTTPS certificate renewal works correctly after fixing #1271, hopefully this will never happen again. That said, if you heavily use the app, I'd really suggest self-hosting and not relying on the free service :)

Great

**Comment by shinyzhu** [comment] 2024-01-02 01:50
Thank you @laymonage and happy new year.

**Comment by alec-c4** [comment] 2025-01-26 08:59
@laymonage, may I ask you to check the logs? What's wrong with my setup? I'm not sure, but it looks like "." or "-" characters may cause this effect.

**Comment by alec-c4** [comment] 2025-01-27 09:42
I've enabled giscus access to all repos, but not only one I use for my blog, and it works now. Looks like a bug
