### ISSUE TITLE
Bug: Crash on unknown locale. (Would you accept a PR?)

### ISSUE THREAD

**Issue by dogweather** [giscus/giscus#1358] opened 2024-04-16 01:08 UTC
Hindi, code: `hi` isn't in the locales. The browser app crashes.

How about a default language setting if the desired language isn't available.

Would you accept a PR?

**Comment by laymonage** [comment] 2024-12-31 21:21
Closing as a duplicate of #620, PRs welcome. Thanks!

**Closed by laymonage** 2024-12-31 21:21 UTC
