### ISSUE TITLE
Reverse order of comments

### ISSUE THREAD

**Issue by hmsjy2017** [giscus/giscus#371] opened 2022-01-26 03:50 UTC
Is it possible to sort the comments in reverse order? Whenever I wanted to comment, I had to scroll to the bottom of the page.

**Comment by laymonage** [comment] 2022-01-26 04:04
Duplicate of #157 and #75. PR in #358.

**Closed by laymonage** 2022-01-26 04:04 UTC

**Comment by laymonage** [comment] 2022-01-26 15:40
This is now possible as of #358 and #372.
