### ISSUE TITLE
non github users

### ISSUE THREAD

**Issue by karkir0003** [giscus/giscus#839] opened 2023-01-01 03:25 UTC
i noticed that in the readme, it was mentioned that visitors can comment directly in the forum with giscus app. however when i go to sample hosted website, i see that in the github discussion forum embedded, you have to sign in with github. so does that mean for users to directly post in forum, they have to sign in or make a github account?

**Comment by nschonni** [comment] 2023-01-01 03:27
https://github.com/giscus/giscus/issues/65

**Comment by laymonage** [comment] 2023-01-01 09:02
> Alternatively, visitors can comment on the GitHub Discussion directly.

It just means that instead of using giscus, visitors can also open the discussion on GitHub and leave a comment on GitHub directly, instead of via giscus.

Currently GitHub sign-in is required. Closing as duplicate of #65.

**Closed by laymonage** 2023-01-01 09:02 UTC
